### ISSUE TITLE
I created a HTMLSnippet context version

### ISSUE THREAD

**Issue by ChrisdeG** [mendix/HTMLSnippet#10]
For[ Stephan Bruijnis Tag Manager ](http://www.stukkie.nl/mendix/using-google-tag-manager-with-mendix/)  I merged the format string code with the HTMLSnippet to create a HTMLSnippet context version. This enable the  google tag manager stuff.

Would be nice to include this in the standard. I provide the renamed widget in a the attached file.
[HTMLSnippetContext.zip](https://github.com/mendix/HTMLSnippet/files/140869/HTMLSnippetContext.zip)

**Comment by JelteMX** [comment]
Thanks! I checked out your code and I cannot include this right away. There are a few problems with the code:

- The update method needs to be fixed. See https://github.com/mendix/GoogleMapsWidget/issues/9. This has to do with the fact that the callback needs to be called when the widget is rendered. In this case ``callback`` needs to be passed to ``loadData`` so it can be called when the widget is rendered. (This is a common issue now that we are trying to fix everywhere)
- When ``obj`` is empty in ``callback``, the method ``_loadData`` will do nothing (it returns). Yet, if you have a widget that uses a context, it should render empty when the object is missing
- Last but not least, you do not have a ``_resetSubscriptions`` method. If the context changes, it needs to be able to know which method to call.

If I am mistaken, please let me know. I'll review the code and see if we can create a context version of this widget using your code.

**Comment by Mcpoowl** [comment]
Hi Chris ( @ChrisdeG ),

Are you prepared to fix the issues Jelte brought up? We're running into a situation where we'd love to use this context version.

Is is 'production ready' in it's current state?

**Comment by Andries-Smit** [comment]
Stale issue. If it is still relevant, please re-open. Cheers
