### ISSUE TITLE
Being able to embed entity data into the javascript/html

### ISSUE THREAD

**Issue by gnmarcos** [mendix/HTMLSnippet#14]
I want to be able to use entity data within my javascript/html in the contents property. Another alternative would be to just allow the javascript/html to be loaded from a microflow.

Thanks
Gonçalo

**Comment by rik-bos** [comment]
You may use: 
```js
// Get the context of the HTMLsnippet Widget.
var context = this.mxcontext

// Get the MxObject of the context
var contextObj = context.getTrackObject();
```
This will give you the MxObject if available: https://apidocs.mendix.com/6/client/mendix_lib_MxObject.html.

The latest version of the widget allows you to do an update on refresh / reload of the object. However, I  would really recommend you to write your own widget if you need entity specific logic.

 

See: https://github.com/mendix/generator-mendix, https://github.com/mendix/AppStoreWidgetBoilerplate and https://world.mendix.com/display/refguide6/XML+Reference+Guide for more details on how to do this.

See also: https://forum.mendixcloud.com/link/ideas/117
