### ISSUE TITLE
Contents is affected by alternate language settings

### ISSUE THREAD

**Issue by brickers** [mendix/HTMLSnippet#17]
Hi there

I recently found out that the contents attribute of this widget is affected by alternate languages. The two things I have seen are:
- when content type is HTML, additional angle brackets are added around the contents, similar to how labels are shown when no translation for that language has been entered
- when content type is javascript, contents is lost between different languages - whatever is coded in one language does not carry across to other languages!

Thanks
Ferg

**Comment by Andries-Smit** [comment]
Indeed the content is of type translatableString. This allows you to change the contant for each language. This makes sense for HTLM, less for JavaScript.

The issue you describes is in the custom widget functionality of the Mendix modeler/ Studio Pro not in the widget itself.

For now just copy past that content
