### ISSUE TITLE
Way to have multiple external js for html

### ISSUE THREAD

**Issue by joshianurag21** [mendix/HTMLSnippet#19]
Hi there

I have a requirement to show some 3D views in the mendix form. I have already achieved this using html and javascript, but to have this as a part of mendix form, I am using HTMLSnippet. For this, I need to import multiple js files in html, so is there any way to achieve this using HTMLSnippet addon on mendix form.

I will be importing js as shown below:
<script src="js/index.js"></script>

where should we put index.js in the project directory structure.

**Comment by Andries-Smit** [comment]
No the widget will only load a single file.
For more complex snippets it is recommend to build a widget form scratch. 
https://docs.mendix.com/howto/extensibility/widget-development

Your way of adding them to index.html is an acceptable workaround in combination of the snippet.
