### ISSUE TITLE
How to get context

### ISSUE THREAD

**Issue by armands9186** [mendix/HTMLSnippet#20]
In my project i have a dataview from which I want to read data and apply some javascript. In my case I only need to know if the entity object is not empty. So I put HtmlSnippet with Context in a dataview. I want to perform animation if the object is not null. I don't how to access this context with the snippet.

**Comment by rik-bos** [comment]
You should be able to use:
`this.contextObj`

It is set at: https://github.com/mendix/HTMLSnippet/blob/master/src/HTMLSnippet/widget/HTMLSnippet.js:104

**Comment by armands9186** [comment]
Thanks for the answer. But how to get the actual object the data view is holding? Also this.contextObject tests true when data view object is empty.

**Comment by rik-bos** [comment]
Might this one help you: https://github.com/mendix/HTMLSnippet/issues/14#issuecomment-261871235
For accessing the data see: https://apidocs.mendix.com/7/client/mendix_lib_MxObject.html

**Comment by armands9186** [comment]
For some reason this.contextObj is undefined when jQuery is enabled. With javascript only it's seems to be working.

**Comment by rik-bos** [comment]
That's a scope thing. You could consider writing a widget?

**Comment by Andries-Smit** [comment]
If this issues keeps on going, please find you way to the forum, questions on how to use the widget should continue there. Cheers

**Comment by Andries-Smit** [comment]
please note that `this.mxcontext` is also available in the newer version of Mendix
