### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by JamesRamm** [mendix/HTMLSnippet#22]
Im trying to use HTMLSnippet with an external JS file. I have created a folder - 'assets' in the 'theme' folder of the mendix project; which contains a 'test.js' file.

When I try to load the page with the HTMLSnippet; I get a 404 error:

mxui.js?636930074019343272:5 GET http://localhost:18080/p/assets/test.js?v=1557404458549 net::ERR_ABORTED 404 (Not Found)

I can see that the 'assets' folder has been copied to 'deployment/web'

My widget configuration looks like:
![image](https://user-images.githubusercontent.com/2784823/57453279-49173880-7266-11e9-898c-01d920cb35cf.png)

Any ideas?

**Comment by rik-bos** [comment]
As you can see on the error the /p/ (for the native deeplinks) is working
against you. Can you try setting the path in the widget to /assets/test.js

That first slash should trigger the browser to look in the webroot.

Kind regards,
Rik

**Comment by JamesRamm** [comment]
Thanks yes that works! 
Could be good to provide a bit more clarification on this in the docs and also on `contextObj` (which is not mentioned in the documentation anywhere)

**Comment by rik-bos** [comment]
Hi James,

I'll do a pull request on the documentation for the initial slash.

For the documentation regarding the contextObj, I think it's bad practice to build a lot of functionality around the contextObj in an HTML snippet, that will be hard to maintain and hard to read. I'd advice you to build a custom widget instead, that will give you much more control and actually it is not that hard if you use the boilerplate.

For some kickstart on this you can check:
- https://docs.mendix.com/howto/widget-development/
- https://apidocs.mendix.com/7/client/mendix_lib_MxObject.html (Mx Client API regarding the contextObj)

Kind regards,
Rik Bos

**Comment by Andries-Smit** [comment]
@rik-bos Thanks for the pull request.
