### ISSUE TITLE
I get the current 404 in Mendix 5.15

### ISSUE THREAD

**Issue by simo101** [mendix/HTMLSnippet#3]
404 - file not found for file: mxclientsystem/HTMLSnippet/widget/HTMLSnippet.js

I have looked into the widget can can't see anything obvious wrong with the naming or referencing in the widget.

**Comment by Rvthof** [comment]
Seems its missing the /widgets/ folder in there.

Should be:

mxclientsystem/**widgets/**HTMLSnippet/widget/HTMLSnippet.js

**Comment by t-fitz** [comment]
Hi Simon, 

I've tried the HTMLSnippet.mpk from the Mendix appstore and the release section for this repository and can display a simple paragraph tag or console.log ok.

Could you give some more info about which version of the widget you are using and what you are trying to do with it.

Thanks
Trevor

**Comment by melvingrootenboers** [comment]
Not reproducable (discussed with Simon)
