### ISSUE TITLE
Use of templating in case the widget is placed in a dataview

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/HTMLSnippet#8]
Just an enhancement, but it would be great if we could use templating in the HTMLsnippet if it is placed in a dataview. With it we could use data from our domain model in the widget!

**Comment by RoelandSalij** [comment]
Hi Paul,
Isn't this something you can accomplish with the FormatString widget?
If you're using Mx 5.21 or higher you can also make use of templating, in a dataview, utilizing the newly built-in text widget.

If these suggestions don't comply with your use case, we are curious what your use case is!

**Comment by Mcpoowl** [comment]
Hi Roeland,

That might just be the case, since you can render the contents as HTML.. Now I remember, I might even have suggested that solution to someone myself...

The use case was that I had to create extra HTML element to be able to add classes to those, for example to use FontAwesome with <i> element and <span> elements. That's perfectly doable with the HTML snippet and static content (see screenshot:

![image](https://cloud.githubusercontent.com/assets/2244753/12138960/22f60c8c-b45d-11e5-90e0-46e77383c623.png) )

However, I would like if the data in that screenshot is actually data from my Entity..

I'll try to see if the formatString widget will suffice! Still not awake I guess ;-). Thanks for the reminder!
